apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      protocol: {{ $value.protocol }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
    {{- end }}
